services:
  mysql:
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql_passwd
      MYSQL_DATABASE: kestra
    ports:
      - "63306:3306"
    volumes:
      - ${PWD}/data:/tmp/docker

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: pg_passwd
      PGPASSWORD: pg_passwd
    ports:
      - "65432:5432"
    volumes:
      - ${PWD}/data:/tmp/docker

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "57017:27017"
    volumes:
      - ${PWD}/data:/tmp/docker

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: SQLServer_Passwd
      ACCEPT_EULA: Y
    ports:
      - "57037:1433"
    volumes:
      - ${PWD}/data:/tmp/docker

  oracle:
    image: gvenzl/oracle-free
    environment:
      ORACLE_PASSWORD: oracle_passwd
    ports:
      - "57057:1521"
    volumes:
      - ${PWD}/data:/tmp/docker
